


CREATE TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB
(
  ALC_ID                          NUMBER(9)     NOT NULL,
  ALC_NOMBRE                      VARCHAR2(80 BYTE) NOT NULL,
  ALC_TAMANIO                     NUMBER(15,2)  DEFAULT 0,
  ALC_FECHA_CREACION              DATE,
  ALC_MDS_ID                      NUMBER(9),                         
--  ALC_PROCESADO                   VARCHAR2(10 BYTE),
  ALC_CANTIDAD_REGISTROS          NUMBER(9)     DEFAULT 0,
  ALC_CANTIDAD_REGISTROS_OK       NUMBER(9)     DEFAULT 0,
  ALC_CANTIDAD_REGISTROS_ERR      NUMBER(9)     DEFAULT 0,
  ALC_HASH                        VARCHAR2(32 BYTE),
  ALC_USUARIO_ALTA                VARCHAR2(128 BYTE) NOT NULL,
  ALC_FECHA_ALTA                  DATE          NOT NULL,
  ALC_USUARIO_ULT_MOD             VARCHAR2(128 BYTE) NOT NULL,
  ALC_FECHA_ULT_MOD               DATE          NOT NULL,
  ALC_USUARIO_BAJA                VARCHAR2(128 BYTE),
  ALC_FECHA_BAJA                  DATE
);

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_NOMBRE IS 'Nombre del archivo';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_TAMANIO IS 'Tamaño del archivo en bytes';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_FECHA_CREACION IS 'Fecha de creación del archivo por el medidor';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_MDS_ID IS 'ID del medidor que generó el archivo';

--COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_PROCESADO IS 'OK= Procesado correctamente - ERROR = Procesado con algún error en los registros de detalle ';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_CANTIDAD_REGISTROS IS 'Cantidad total de registros que contiene el archivo';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_CANTIDAD_REGISTROS_OK IS 'Cantidad de registros procesados OK';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_CANTIDAD_REGISTROS_ERR IS 'Cantidad de registros procesados con ERROR';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB.ALC_HASH_MD5 IS 'Hash MD5 para verificar la integridad del archivo';




CREATE TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET
(
  ALD_ID                          NUMBER(9)     NOT NULL,
  ALD_ALC_ID                      NUMBER(9)     NOT NULL,
  ALD_FECHA                       DATE          NOT NULL,
  ALD_HORA                        DATE          NOT NULL,
  ALD_INSTALACION                 VARCHAR2(20 BYTE) NOT NULL,
  ALD_MEDIDOR                     VARCHAR2(10 BYTE) NOT NULL,
  ALD_TEMPERATURA                 NUMBER(9,2),
  ALD_PRESION                     NUMBER(9,2),
  ALD_CAUDAL_INSTANTANEO_GROSS    NUMBER(9),
  ALD_ACUMULADOR_GROSS_NO_RESETE  NUMBER(9),
  ALD_ACUMULADOR_PUSOS_BRUTOS_NO  NUMBER(9),
  ALD_FACTOR_K_DEL_MEDIDOR        NUMBER(9),
  ALD_ALTURA_LIQUIDA              NUMBER(9,2),
  ALD_ACUMULADOR_MASA_NO_RESETE   NUMBER(9),
  ALD_VOLUMEN_ACUMULADO_24_HS     NUMBER(9,3),
  ALD_VOLUMEN_ACUMULADO_HOY       NUMBER(9,3),
  ALD_SH2                         NUMBER(9,2),
  ALD_N2                          NUMBER(9,2),
  ALD_C6_MAS                      NUMBER(9,2),
  ALD_NC5                         NUMBER(9,2),
  ALD_DENSIDAD_RELATIVA           NUMBER(12,5),
  ALD_CO2                         NUMBER(9,2),
  ALD_CAUDAL_INSTANTANEO_A_9300   NUMBER(9),
  ALD_C1                          NUMBER(9,2),
  ALD_C2                          NUMBER(9,2),
  ALD_C3                          NUMBER(9,2),
  ALD_IC4                         NUMBER(9,2),
  ALD_NC4                         NUMBER(9,2),
  ALD_IC5                         NUMBER(9),
  ALD_PODER_CALORIFICO            NUMBER(9),
  ALD_USUARIO_ALTA                VARCHAR2(128 BYTE) NOT NULL,
  ALD_FECHA_ALTA                  DATE          NOT NULL,
  ALD_USUARIO_ULT_MOD             VARCHAR2(128 BYTE) NOT NULL,
  ALD_FECHA_ULT_MOD               DATE          NOT NULL,
  ALD_USUARIO_BAJA                VARCHAR2(128 BYTE),
  ALD_FECHA_BAJA                  DATE
);

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET.ALD_FECHA IS 'Formato: DD/MM/YYYY';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET.ALD_HORA IS 'Indicar solo Hora y Minutos.-';

COMMENT ON COLUMN REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET.ALD_INSTALACION IS 'Verificar la existencia en la tabla TLM_MEDIDORES_FISCALES';





CREATE TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR
(
  ALE_ID               NUMBER(9)                NOT NULL,
  ALE_ALC_ID           NUMBER(9)                NOT NULL,
  ALE_REGISTRO         VARCHAR2(1000 BYTE)      NOT NULL,
  ALE_NRO_LINEA_ERROR  NUMBER(9)                NOT NULL,
  ALE_MENSAJE_ERROR    VARCHAR2(1000 BYTE)      NOT NULL,
  ALE_USUARIO_ALTA     VARCHAR2(128 BYTE)       NOT NULL,
  ALE_FECHA_ALTA       DATE                     NOT NULL,
  ALE_USUARIO_ULT_MOD  VARCHAR2(128 BYTE)       NOT NULL,
  ALE_FECHA_ULT_MOD    DATE                     NOT NULL,
  ALE_USUARIO_BAJA     VARCHAR2(128 BYTE),
  ALE_FECHA_BAJA       DATE
);




CREATE UNIQUE INDEX REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB_PK ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB
(ALC_ID);


CREATE UNIQUE INDEX REGALIAS.UN_NOM_FEC_BAJ ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB
(ALC_NOMBRE, ALC_FECHA_BAJA);


CREATE UNIQUE INDEX REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET_PK ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET
(ALD_ID);


CREATE UNIQUE INDEX REGALIAS.UN_ALC_FECHA_HORA_FEC_BAJ ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET
(ALD_ALC_ID, ALD_FECHA, ALD_HORA, ALD_FECHA_BAJA);


CREATE UNIQUE INDEX REGALIAS.UN_INST_MED_FECHA_HORA_FEC_BAJ ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET
(ALD_INSTALACION, ALD_MEDIDOR, ALD_FECHA, ALD_HORA, ALD_FECHA_BAJA);


CREATE UNIQUE INDEX REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR_PK ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR
(ALE_ID);

CREATE INDEX REGALIAS.NU_ALE_ALC_ID ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR
(ALE_ALC_ID);




ALTER TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB ADD (
  CONSTRAINT TLM_ARCHIVOS_LECTURAS_RES11_CAB_PK
 PRIMARY KEY
 (ALC_ID));

ALTER TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB ADD (
  CONSTRAINT FK_CAB_MDS 
 FOREIGN KEY (ALC_MDS_ID) 
 REFERENCES REGALIAS.TLM_MEDIDORES (MDS_ID));

 
ALTER TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET ADD (
  CONSTRAINT TLM_ARCHIVOS_LECTURAS_RES11_DET_PK
 PRIMARY KEY
 (ALD_ID));

ALTER TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET ADD (
  CONSTRAINT FK_CAB_DET 
 FOREIGN KEY (ALD_ALC_ID) 
 REFERENCES REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB (ALC_ID);


ALTER TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR ADD (
  CONSTRAINT TLM_ARCHIVOS_LECTURAS_RES11_ERR_PK
 PRIMARY KEY
 (ALE_ID));

ALTER TABLE REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR ADD (
  CONSTRAINT FK_CAB_ERR 
 FOREIGN KEY (ALE_ALC_ID) 
 REFERENCES REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB (ALC_ID));




CREATE OR REPLACE TRIGGER REGALIAS."RGL_TLM_ARCH_LECTURAS_RES11_CAB" 
   BEFORE DELETE OR INSERT OR UPDATE
   ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB FOR EACH ROW
DECLARE
   fecha DATE := SYSDATE;
BEGIN
   IF INSERTING THEN
      :NEW.ALC_USUARIO_ALTA:=USER;
      :NEW.ALC_FECHA_ALTA:=fecha;
      :NEW.ALC_USUARIO_ULT_MOD:=USER;
      :NEW.ALC_FECHA_ULT_MOD:=fecha;
   ELSIF DELETING THEN
      raise_application_error( -20001, 'No se permite borrar registros de la tabla ');
   ELSIF UPDATING THEN
      :NEW.ALC_USUARIO_ULT_MOD:=USER;
      :NEW.ALC_FECHA_ULT_MOD:=fecha;
   END IF;
END;
/


CREATE OR REPLACE TRIGGER REGALIAS."RGL_TLM_ARCH_LECTURAS_RES11_DET" 
   BEFORE DELETE OR INSERT OR UPDATE
   ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET FOR EACH ROW
DECLARE
   fecha DATE := SYSDATE;
BEGIN
   IF INSERTING THEN
      :NEW.ALD_USUARIO_ALTA:=USER;
      :NEW.ALD_FECHA_ALTA:=fecha;
      :NEW.ALD_USUARIO_ULT_MOD:=USER;
      :NEW.ALD_FECHA_ULT_MOD:=fecha;
   ELSIF DELETING THEN
      raise_application_error( -20001, 'No se permite borrar registros de la tabla ');
   ELSIF UPDATING THEN
      :NEW.ALD_USUARIO_ULT_MOD:=USER;
      :NEW.ALD_FECHA_ULT_MOD:=fecha;
   END IF;
END;
/


CREATE OR REPLACE TRIGGER REGALIAS."RGL_TLM_ARCH_LECTURAS_RES11_ERR" 
   BEFORE DELETE OR INSERT OR UPDATE
   ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR FOR EACH ROW
DECLARE
   fecha DATE := SYSDATE;
BEGIN
   IF INSERTING THEN
      :NEW.ALE_USUARIO_ALTA:=USER;
      :NEW.ALE_FECHA_ALTA:=fecha;
      :NEW.ALE_USUARIO_ULT_MOD:=USER;
      :NEW.ALE_FECHA_ULT_MOD:=fecha;
   ELSIF DELETING THEN
      raise_application_error( -20001, 'No se permite borrar registros de la tabla ');
   ELSIF UPDATING THEN
      :NEW.ALE_USUARIO_ULT_MOD:=USER;
      :NEW.ALE_FECHA_ULT_MOD:=fecha;
   END IF;
END;
/


GRANT DELETE, INSERT, SELECT ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB TO GLASTRA;

GRANT DELETE, INSERT, SELECT ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET TO GLASTRA;

GRANT DELETE, INSERT, SELECT ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR TO GLASTRA;

GRANT DELETE, INSERT, SELECT ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB TO MCALLAEY;

GRANT DELETE, INSERT, SELECT ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET TO MCALLAEY;

GRANT DELETE, INSERT, SELECT ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR TO MCALLAEY;

GRANT DELETE, INSERT, SELECT, UPDATE ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_CAB TO OIRRAZA;

GRANT DELETE, INSERT, SELECT, UPDATE ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_DET TO OIRRAZA;

GRANT DELETE, INSERT, SELECT, UPDATE ON REGALIAS.TLM_ARCHIVOS_LECTURAS_RES11_ERR TO OIRRAZA;

